---
title: "Repdata"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
  library(readr)
Repdata <- read_csv("~/Documents/R/repdata_data_activity.zip")
```

first we find the total number of steps
```{r}
stepsbyday <- aggregate(steps~date, Repdata, sum)
```

Histogram of total number of steps a day
```{r}
hist(stepsbyday$steps)
```
 
mean and median number of steps per day
```{r}
mean(stepsbyday$steps)
median(stepsbyday$steps)
```
 
histogram of mean steps by intreval
```{r}
meaninterval <- aggregate(steps~interval, Repdata, mean)
plot(meaninterval$interval, meaninterval$steps, type= "l")
```


maximum number of steps
```{r}
meaninterval[which.max(meaninterval$steps), ]
```

number of NAs 
```{r}
sum(is.na(Repdata$steps))
```

change NAs to mean value of the interval
```{r}
fillvalue <- function(steps, interval) {
  filled <- NA
  if (!is.na(steps)) 
    filled <- c(steps) else filled <- (meaninterval[meaninterval$interval == interval, "steps"])
    return(filled)
}
filledData <- Repdata
filledData$steps <- mapply(fillvalue, filledData$steps, filledData$interval)
```

plot filled mean
```{r}
filledmean<- aggregate(steps~date, filledData, sum)
hist(filledmean$steps)
```

mean and median of new data
```{r}
mean(filledmean$steps)
median(filledmean$steps)
```

weekday vs weekend graph
```{r}
weekday.or.weekend <- function(date) {
     day <- weekdays(date)
     if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")) 
            return("weekday") else
                 return("weekend")
}
filledData$date <- as.Date(filledData$date)
filledData$day <- sapply(filledData$date, FUN = weekday.or.weekend)
```

plot of steps by average interval for weekdays or weekends
```{r}
library(ggplot2)
means <- aggregate(steps~interval + day, data = filledData, mean)
ggplot(means, aes(interval, steps)) + geom_line() + facet_grid(day~.)+
  xlab("5-minute interval") + ylab("Number of steps")
```
